version: '2'
services:
    web:
        build: .
        ports:
            - "8080:3000"
        depends_on:
            - db
        volumes:
            - ./app:/usr/src/app
        environment:
            - NODE_ENV=dockerdev
    db:
        image: mongo:latest
        expose: 
            - "27017"